engines:
  pmd:
    enabled: true
    channel: "beta"
  checkstyle:
    enabled: true
    config:
      file: "checkstyle.xml"
    channel: "beta"

ratings:
  paths:
  - "**.java"

exclude_paths:
- "src/main/java/io/dropwizard/jersey/protobuf/protos/DropwizardProtos.java"
- "src/test/java/io/dropwizard/jersey/protobuf/protos/DropwizardProtosTest.java"
